### ISSUE TITLE
Latest 4 solc versions are missed.

### ISSUE THREAD

**Issue by Latrasis** [ethereum/solc-js#10]
When listing the remote versions the loop misses the last 4 versions in the list.

```js
for (var i = sources.length - 1; i >= 0; i--) {
    // FIXME: use build as well
    var version = sources[i].match(/^soljson-v([0-9.]*)-.*.js$/);

    // Skip invalid lines
    if (!version) {
      continue;
    }

    if (version[1] === wanted) {
      downloadBinary(sources[i].match(/^soljson-(.*).js$/)[1]);
      return;
    }
  }
```

**Comment by axic** [comment]
@Latrasis as an improvement it would be nice to improve solc-bin by having the versions in a JSON file. 

solc-bin contains [list.txt](https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.txt) and [list.js](https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.js) for the versions. The latter has two fields: `versions` (equals to list.txt) and `releases` (which is the first build of each version).

Do you think you could improve the process in solc-bin? That could help solc-js :)

**Comment by Latrasis** [comment]
@axic: Sure thing! Just to understand the process, what is the process of adding a new version? Is the `list.txt` appended to? Or is it generated?

**Comment by axic** [comment]
@Latrasis both are generated by [this script](https://github.com/ethereum/solc-bin/blob/gh-pages/update-index.sh)

**Comment by chriseth** [comment]
Can you please explain a bit more why you think this is a bug?

**Comment by Latrasis** [comment]
The very reason I stumbled upon this was when the latest version`3.2` got an update on `soljson-v0.3.2-2016-05-06-9e36bdd.js` which allowed inlined library contracts: https://github.com/ethereum/solidity/issues/493. This technically should have been `3.3`, but it was still `3.2`.

The realtime solidity compiler (RSC) does fetch latest version, however `solc-js` didn't which meant that any contract that would compile on RSC, but would not compile on `truffle` or other tools. Logically to me both should have the same latest version.

**Comment by chriseth** [comment]
Ok, thanks, now I understand. The "inline library functions" feature is not yet released. It is part of the nightly developer snapshots that are used by browser-solidity. Version 0.3.3 will be released as soon as solidity is stable enough and it will of course contain this new feature.

The npm version is created for releases only in order to prevent people from deploying contracts with non-release versions (which are less stable and harder to verify because they might not be as well archived as the released versions).

Using `loadRemoteVersion('latest')`, you can always get the latest version just as browser-solidity does, but I think it is not a good idea to release a new npm version with every development snapshot.

The reason why browser-solidity uses development snapshots is because it is trivial to switch back to an older version if something goes wrong.

**Comment by axic** [comment]
@chriseth if this versioning/build behaviour is not explained in the documentation (readthedocs), it should be. cc @Denton-L

**Comment by Denton-L** [comment]
Sorry, I'm not too familiar with web development. Just to make sure I'm updating the documentation correctly, if I wanted to use the latest development snapshot, I'd do the following?

```javascript
var solc = require('solc');
var snapshot = solc.loadRemoteVersion('latest');
```

**Comment by axic** [comment]
@Denton-L thank you! Answered your question on the PR.

**Comment by Latrasis** [comment]
@chriseth Alrighy, but as a suggestion how about using `stable`, and `nightly` version labels instead? This is more semantic to me than simply using `latest` with can be ambiguous, and is a common used practice that has proved itself within many projects.

**Comment by chriseth** [comment]
@Latrasis yes, good idea!
