### ISSUE TITLE
UnimplementedFeatureError: Nested arrays not yet implemented

### ISSUE THREAD

**Issue by ahmedeid6842** [ethereum/solc-js#530]
- I got this error when passing array of string in the function parameters 
- It work as expected in remix's compiler but in "solc" don't 

pragma solidity ^0.4.17;
pragma experimental ABIEncoderV2;

![Captur63e](https://user-images.githubusercontent.com/57197702/123495452-0d957f00-d624-11eb-8c76-cd8640ea70fc.PNG)

**Comment by cameel** [comment]
@ahmedeid6842 I could probably tell you more if you posted a complete code snippet but I'm pretty sure the difference you're seeing is because you're using different versions of the compiler in Remix and with solc-js. The default in Remix is currently 0.8.4 and it has had a lot of bugfixes and new feature since 0.4.17. 0.4.17 is very old at this point and I recommend upgrading to a newer one that has this problem resolved.
