### ISSUE TITLE
`TypeError: Error resolving module specifier “solc/wrapper”` when trying to import solc-js in a browser

### ISSUE THREAD

**Issue by RickCastle2018** [ethereum/solc-js#627]
I've added this line into my index.html file: `<script type="text/javascript" src="https://binaries.soliditylang.org/bin/soljson-v0.8.4+commit.c7e474f2.js"></script>`

So, as it's written in README I have `window.Module` variable, and I have to 'wrap' it accordingly to the instructions:

```
import * as wrapper from 'solc/wrapper';
const solc = wrapper(window.Module);
```

I added these lines into separate <script> block (placed after the first), but now I get this error in the browser console: `Uncaught TypeError: Error resolving module specifier “solc/wrapper”. Relative module specifiers must start with “./”, “../” or “/”`

Could you please tell what I was doing wrong?

P.S. There's also require() function option listed in Browser Usage. But how? Require() is only for Node.js usage as I know

**Comment by cameel** [comment]
How are you installing/accessing solc-js inside the browser? This sounds a bit as if you just loaded the binary without having the library available.

We'll need a bit more details to debug this. Can you provide a more complete example to reproduce this? Which browser are you using?

**Comment by RickCastle2018** [comment]
@cameel, sorry for long responce. The problem is documentation is not clear at all (for browser usage). I found that compiler should be somehow loaded to service worker (https://github.com/ethereum/remix-project/blob/614f726d94384a846a4c8cac81d5c802ff42ba12/libs/remix-solidity/src/compiler/compiler-worker.ts). But I still dont understand how... Could you please write complete guide for this?

**Comment by RickCastle2018** [comment]
![image](https://user-images.githubusercontent.com/48931166/172057169-e47c8918-8e68-42ec-af26-88e31258c765.png)
Here're my attempts. I'm trying to use Web Workers, not Service Workers

**Comment by r0qs** [comment]
Hi @RickCastle2018 what version of solc-js are you using?
When you opened the issue you state that were using `soljson-v0.8.4+commit.c7e474f2.js` but in your example you use `v0.4.5`.

You are correct about the `require`, but I believe this also apply to ES6 imports, since nodejs doesn’t natively support ES6 import directly as far as I know. The easy way is to bundle your modules need using [browserify](https://browserify.org/) or [webpack](https://webpack.js.org/) with babel.

Here a working example based on your code using the version `v0.8.4`. Please note that this is just an example and does not handle any errors. You should adapt it to your use case:
* index.html
```html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
</head>

<body>
	<script>
		var worker = new Worker('./dist/bundle.js');
		worker.addEventListener('message', function (e) {
			const output = e.data.output
			for (var contractName in output.contracts['contract']) {
				console.log(`Bytecode of contract: ${contractName}: ${output.contracts['contract'][contractName].evm.bytecode.object}`);
			}
		}, false);

		worker.postMessage({
			contractCode: 'contract C { function f() public { } }',
		})
	</script>
</body>

</html>
```
* worker.js:
```javascript
importScripts('https://binaries.soliditylang.org/bin/soljson-v0.8.4+commit.c7e474f2.js')
import wrapper from 'solc/wrapper';

self.addEventListener('message', (e) => {
	const contractCode = e.data.contractCode
	const sourceCode = {
		language: 'Solidity',
		sources: {
			contract: {
				content: contractCode,
			}
		},
		settings: {
			outputSelection: {
				'*': {
					'*': ['*']
				}
			}
		}
	};

	const compiler = wrapper(self.Module)
	self.postMessage({
		output: JSON.parse(compiler.compile(JSON.stringify(sourceCode)))
	})
}, false)
```

But indeed the documentation seems to be wrong. Since the default import is already an alias so `import * as wrapper from 'solc/wrapper';` does not work and returns `wrapper is not a function` for the example above.

As alternatives you can use the method that I used above, use the `require` form, or:
```js
import * as wrapper from 'solc/wrapper';
const compiler = wrapper.default(self.Module);
```
```js
import {default as wrapper} from 'solc/wrapper' // it is a bit strange to do and not sure how this can be useful for you, but it works.
const compiler = wrapper(self.Module);
```

To test this you can use browserify, install solc-js in your project and do:
```
npx browserify ./worker.js > ./dist/bundle.js -t babelify
chromium --allow-file-access-from-files index.html
```
As chrome may complain about accessing local files, you may need to add the flag `--allow-file-access-from-files` while testing in case you are not using a framework to develop your project. Please do not allow this option when browsing the internet since this is a [security feature](https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_switches.cc?q=kAllowFileAccessFromFiles&ss=chromium).
