### ISSUE TITLE
Yul: too deep in the stack

### ISSUE THREAD

**Issue by drop19** [ethereum/solc-js#645]
I'm getting the following exception during compilation with Yul. I didn't use assembly directly except in libraries.

solidity setting:
```
      {
        version: '0.8.15',
        settings: {
          viaIR: true,
          optimizer: {
            enabled: true,
            runs: 10000,
          },
        },
      },
```

```
YulException: Cannot swap Variable var_amount with Slot RET[fun_fromWad]: too deep in the stack by 1 slots in [ RET expr_7734_address var_liquidity _5 _5 _8 _5 _11 _9 _10 _8 _4 _1 _5 expr_7741_component expr_7727_address expr_1 expr_7734_address TMP[iszero, 0] RET[fun_fromWad] ]
No memoryguard was present. Consider using memory-safe assembly only and annotating it via 'assembly ("memory-safe") { ... }'.
```

**Comment by cameel** [comment]
This is not a bug, but a limitation of the compiler. You have too many parameters/stack variables somewhere in your code and the EVM is running out of stack slots (there are only 16 accessible at any time). You're also apparently not using the memory-safe annotation on your inline assembly blocks so the compiler cannot use the mechanism for moving variables to memory. Please try doing what the error message suggests. Here are the docs on that: [Memory Safety](https://docs.soliditylang.org/en/latest/assembly.html#memory-safety).

**Comment by cameel** [comment]
Ah, wait you wrote that you're using Yul directly. In that case the situation is similar but instead of the annotation you need to manually use the [`memoryguard`](https://docs.soliditylang.org/en/latest/yul.html#memoryguard). But please read the docs carefully. By using it you promise that your code behaves well in certain ways essential to the memory escalation mechanism.
