### ISSUE TITLE
Add Support for Compiling yul

### ISSUE THREAD

**Issue by chase-manning** [ethereum/solc-js#650]
The Solidity Compiler supports compiling `.yul` files to binary. It would be great to have this functionality in `solc-js` 😄

**Comment by cameel** [comment]
I think you mean the [`solcjs`](https://github.com/ethereum/solc-js/blob/master/solc.ts) script? Because solc-js as a library does support Yul - to use it just set the language to `Yul` in [StandardJSON](https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description).

As for the script, it was meant to be a simple helper and we do not think it makes much sense to put effort into extending it. We don't think it's seeing much production use anyway. For CLI use we recommend using one of the [native binaries](https://github.com/ethereum/solc-bin/). They have a very extensive set of CLI options.

**Comment by chase-manning** [comment]
Oh thanks so much! Didn't realise you could set the language as `Yul`, user error ha ha. Appreciate the response 😄 

Got it working now 🎉
