### ISSUE TITLE
Does solc.loadRemoteVersion() download a new version of solc each time it is run?

### ISSUE THREAD

**Issue by alexreyes** [ethereum/solc-js#676]
I've been using `solc.loadRemoteVersion()` to compile several projects each running different versions of solc. 

**Every time I compile, is `solc.loadRemoteVersion()` re-downloading the given solc version? Or is it cached?**

**If it's already cached, you can ignore the below questions** (since my main concern is around re-downloading versions of solc each time): 
- How can I view all the solc versions that have been installed? 
- how can I switch to them programatically without re-downloading each time?

Running `solcjs --version`, I only see the newest version available: 

 > `0.8.17+commit.8df45f5f.Emscripten.clang`

### I'll make a PR to update the Readme with this info once I find out!

**Comment by cameel** [comment]
No, there's no caching of any kind. `loadRemoteVersion()` is a very simple function that makes a HTTP request and stores the obtained binary in memory, without ever writing it to disk:
https://github.com/ethereum/solc-js/blob/d6fee850ef21b79b6a237fc0f73e530298e28265/wrapper.ts#L43-L69

If you want to load multiple versions and manage them in some way, you have do it on your own. The loaded binary as a JS module is passed to the callback you provide. Then you can do whatever you want with it.

> Running `solcjs --version`, I only see the newest version available:

Yes, this returns only the version of the current binary. And by "current" I mean the one that is stored in `soljson.js` on disk. `solcjs` is a simple command-line wrapper that mimics the interface of native `solc`.

It never downloads the compiler, neither via `loadRemoteVersion()` or otherwise. Latest binary is always included in the npm package and if you're using the repo directly, you can use `downloadCurrentVersion.ts` to download that binary. `solcjs` works with only one version at at time but you can freely swap the file on disk for something else between invocations.

**Comment by alexreyes** [comment]
Okay, thanks for the info! @cameel
