### ISSUE TITLE
Failed to compile large json inputs

### ISSUE THREAD

**Issue by tovarnakM** [ethereum/solc-js#692]
Hi, I have a compilation related problem (nodejs application crashes) if I try to compile an "input" that is greater than approx. 1.2 MB (the compiler version I am using is `v0.8.18+commit.87f61d96`, but I don't think it matters). Up to 1.2MB everything works fine using `solc.compile(JSON.stringify(input))` API.

If this is a known issue, how do you suggest dealing with large contract json files? I also found some related problem here https://ethereum.stackexchange.com/questions/57770/how-to-solve-max-call-size-stack-exceeded-when-compiling-solidity

Code: https://codesandbox.io/p/sandbox/quirky-joji-vg74pu?file=%2Findex.js%3A3%2C25

**Comment by r0qs** [comment]
Hi @tovarnakM, since the `spurious dragon` hard-fork smart contracts have a size limit of 24576 kb (see: https://eips.ethereum.org/EIPS/eip-170).

So, sadly, as far as I know, the only solution is to reduce the size of your contract. One way to do it is by splitting the logic of your code into multiple contracts and libraries. You can read more about some techniques to accomplish that here: https://ethereum.org/en/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/
