### ISSUE TITLE
Support for `--metadata` flag

### ISSUE THREAD

**Issue by bguiz** [ethereum/solc-js#709]
- `solc` supports the `--metadata` flag, see https://docs.soliditylang.org/en/v0.8.17/metadata.html#contract-metadata
- `solcjs` does not:

```text
$ solcjs --bin --abi --metadata ./account.sol
error: unknown option '--metadata'
```

- I would like to have this available in `solcjs` as well, in order to be able to use it with smart contract verification tools, such as sourcify

**Comment by mehtavishwa30** [comment]
Hey @bguiz! Thanks for bringing this up.

Would love to understand the purpose or motivation behind using the `solcjs` wrapper script rather than native `solc` binary which provides all the options that you may required and aren't intended to make it in the wrapper script.

Please note that if you require options that aren't available in the wrapper script, we recommend you to use the native `solc` binary.

**Comment by bguiz** [comment]
@mehtavishwa30 (1) when using a build tool or framework that already has solcjs baked in. e.g. hardhat, remix, sourcify, etc. (2) for developers who are trialling or building POCs, and aren't that invested, `npm i` is easier than installing the `solc` binary.

> Would love to understand the purpose or motivation behind using the `solcjs` wrapper script rather than native `solc` binary which provides all the options that you may required and aren't intended to make it in the wrapper script.

**Comment by nikola-matic** [comment]
> @mehtavishwa30 (1) when using a build tool or framework that already has solcjs baked in. e.g. hardhat, remix, sourcify, etc. (2) for developers who are trialling or building POCs, and aren't that invested, `npm i` is easier than installing the `solc` binary.
> 
> > Would love to understand the purpose or motivation behind using the `solcjs` wrapper script rather than native `solc` binary which provides all the options that you may required and aren't intended to make it in the wrapper script.

`solcjs` provides full access to the standard JSON interface, which means you can get metadata access via that, so I'm curious as to why you haven't gone for that approach?

**Comment by bguiz** [comment]
@nikola-matic this is great!
> solcjs provides full access to the standard JSON interface,

it sounds like it should then be easier to implement the `--metadata` in the wrapper!
> error: unknown option '--metadata'

**Comment by bguiz** [comment]
bump ☝️ - still waiting on the `--metadata` flag on `solcjs`... is that something that's planned to be added?

**Comment by bguiz** [comment]
If not, how do I get access to the metadata object? I cannot find how to do this in the docs of this repo.
> solcjs provides full access to the standard JSON interface, which means you can get metadata access via that

**Comment by nikola-matic** [comment]
> it sounds like it should then be easier to implement the --metadata in the wrapper!

We have no plans on extending the `solcjs` command line interface, since the Standard JSON interface is the de-facto standard, and provides all of the options that the compiler exposes.

> Pretty much all of the smart verification tools (Sourcify included) use the Standard JSON interface anyway, since it's significantly more comfortable to do so programmatically (e.g. via JS/TS). 

If you want to get the metadata of a contract via the Standard JSON interface, take a look at the [using the compiler docs](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-api) - specifically the `outputSelection`, where there's even an example for requesting the contract metadata. You can also take a look at one of [our tests](https://github.com/ethereum/solidity/tree/develop/test/cmdlineTests/standard_metadata) in the main Solidity repo.

Create your `input.json` file (or whatever you decide to name it), and use `solcjs --standard-json input.json`.

**Comment by bguiz** [comment]
@nikola-matic is it possible to get `solcjs` (not `solc`) to **output** the  Standard JSON interface?

(Either through a CLI flag, or programmatically in a nodejs script?)

**Comment by mehtavishwa30** [comment]
Hey @bguiz! Yes, you can get `solcjs` using `solc.compile()` as shown in the [README](https://github.com/ethereum/solc-js) file. This will output the Standard JSON interface for you.
